// ─── Legal Disclaimer Banner ───────────────────────────────
// Must be shown on every page per SEBON compliance requirements.

import { useState } from 'react';
import { AlertTriangle, X } from 'lucide-react';

export function DisclaimerBanner() {
  const [dismissed, setDismissed] = useState(false);

  if (dismissed) return null;

  return (
    <div className="bg-amber-50 border-b border-amber-200 dark:bg-amber-950/30 dark:border-amber-800">
      <div className="max-w-7xl mx-auto px-4 py-2 flex items-center gap-2 text-xs text-amber-800 dark:text-amber-200">
        <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />
        <span className="flex-1">
          ShareSathi is a <strong>paper trading platform for educational purposes only</strong>. 
          Not registered with SEBON. AI predictions are statistical estimates, not financial advice. 
          Past performance does not guarantee future results.
        </span>
        <button
          onClick={() => setDismissed(true)}
          className="p-0.5 hover:bg-amber-200 rounded dark:hover:bg-amber-800 transition-colors"
          aria-label="Dismiss disclaimer"
        >
          <X className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
}

/** Inline disclaimer for AI prediction pages */
export function AiDisclaimer() {
  return (
    <div className="rounded-lg bg-amber-50 border border-amber-200 p-3 text-xs text-amber-800 dark:bg-amber-950/30 dark:border-amber-800 dark:text-amber-200">
      <div className="flex items-start gap-2">
        <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" />
        <div>
          <p className="font-semibold mb-1">Disclaimer</p>
          <p>
            AI predictions are generated by statistical models (ARIMA) for educational purposes only. 
            They are <strong>NOT financial advice</strong>. ShareSathi is not a registered investment 
            advisor. Always do your own research before making investment decisions. Past performance 
            does not guarantee future results.
          </p>
        </div>
      </div>
    </div>
  );
}

/** Footer disclaimer text */
export function FooterDisclaimer() {
  return (
    <div className="text-xs text-slate-400 dark:text-slate-500 mt-4 pt-4 border-t border-slate-200 dark:border-slate-700">
      <p>
        <strong>Disclaimer:</strong> ShareSathi is a paper trading simulation platform for educational 
        purposes only. No real money is involved in trades. ShareSathi is not registered as an investment 
        advisor with the Securities Board of Nepal (SEBON). AI-generated predictions are statistical 
        estimates and should not be construed as financial advice. Users are solely responsible for their 
        investment decisions. Past performance does not guarantee future results.
      </p>
    </div>
  );
}
